# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b665a9da4c327c3711fdb65ca20d5c6045689162a402aa0df9c0d9b41aef0d23ecaeb80a17eef12f6b2daab072bf30c8831a55ed0b6689069f63a870672f145

test:
  secret_key_base: d73dc06d13aae33aa6227a6ca2d13f5d27f14ba4143be650a4d905ac4f034dc559dc7650ebb86911971fcb9bb807995f95ae13b546a5d25292ec380803d85232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
